#ifndef LWIPOPTS0629
#define LWIPOPTS0629

#define MEM_ALIGNMENT		4
#define SYS_LIGHTWEIGHT_PROT	0

#define TCPIP_THREAD_PRIO	6
#define TCPIP_MBOX_SIZE		16
#define TCPIP_THREAD_STACKSIZE	1024

#define LWIP_PROVIDE_ERRNO	1
#define LWIP_ETHERNET		1

#define ETH_PAD_SIZE		2

#define DEFAULT_THREAD_PRIO	8

#define DEFAULT_THREAD_STACKSIZE	2048
#define DEFAULT_RAW_RECVMBOX_SIZE	16
#define DEFAULT_UDP_RECVMBOX_SIZE	16
#define DEFAULT_TCP_RECVMBOX_SIZE	16
#define DEFAULT_ACCEPTMBOX_SIZE		16

#endif
